import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "creditcards.chase.com", pathname: "/**" },
      { protocol: "https", hostname: "www.chase.com", pathname: "/content/dam/**" },
      { protocol: "https", hostname: "ecm.capitalone.com", pathname: "/WCM/card/**" },
      { protocol: "https", hostname: "icm.aexp-static.com", pathname: "/**" },
      { protocol: "https", hostname: "cdn.robinhood.com", pathname: "/**" },
      { protocol: "https", hostname: "images.ctfassets.net", pathname: "/**" },
      { protocol: "https", hostname: "www.americanexpress.com", pathname: "/content/dam/**" },
      { protocol: "https", hostname: "americanexpress.com", pathname: "/content/dam/**" },
      { protocol: "https", hostname: "www.capitalone.com", pathname: "/**" },
      { protocol: "https", hostname: "ads.capitalone.com", pathname: "/**" },
      { protocol: "https", hostname: "tools.capitalone.com", pathname: "/**" },
      { protocol: "https", hostname: "www.citi.com", pathname: "/**" },
      { protocol: "https", hostname: "www.wellsfargo.com", pathname: "/**" },
      { protocol: "https", hostname: "www01.wellsfargomedia.com", pathname: "/**" },
      { protocol: "https", hostname: "creditcards.wellsfargo.com", pathname: "/**" },
      { protocol: "https", hostname: "www.bankofamerica.com", pathname: "/content/images/**" },
      { protocol: "https", hostname: "www.usbank.com", pathname: "/dam/images/**" },
      { protocol: "https", hostname: "www.discover.com", pathname: "/content/dam/**" },
      { protocol: "https", hostname: "www.discovercard.com", pathname: "/content/dam/**" },
      { protocol: "https", hostname: "www.apple.com", pathname: "/**" },
      { protocol: "https", hostname: "www.sofi.com", pathname: "/**" },
      { protocol: "https", hostname: "www.upgrade.com", pathname: "/**" },
      { protocol: "https", hostname: "x1.co", pathname: "/**" },
      { protocol: "https", hostname: "www.pnc.com", pathname: "/**" },
      { protocol: "https", hostname: "www.truist.com", pathname: "/**" },
      { protocol: "https", hostname: "www.td.com", pathname: "/content/dam/**" },
      { protocol: "https", hostname: "www.navyfederal.org", pathname: "/**" },
      { protocol: "https", hostname: "www.penfed.org", pathname: "/content/dam/**" },
      { protocol: "https", hostname: "www.alliantcreditunion.org", pathname: "/**" },
      { protocol: "https", hostname: "cards.barclaycardus.com", pathname: "/**" },
      { protocol: "https", hostname: "mma.prnewswire.com", pathname: "/**" },
      { protocol: "https", hostname: "www.53.com", pathname: "/**" },
      { protocol: "https", hostname: "www.huntington.com", pathname: "/**" },
      { protocol: "https", hostname: "www.citizensbank.com", pathname: "/**" },
      { protocol: "https", hostname: "cdn-cards.lendingtree.com", pathname: "/**" },
      { protocol: "https", hostname: "ads.regis2.com", pathname: "/**" },
      { protocol: "https", hostname: "framerusercontent.com", pathname: "/**" },
    ],
  },
};

export default nextConfig;
